### ISSUE TITLE
Command 'convert require to import' resulted in an error (Running the contributed command: 'extension.Rona' failed.)

### ISSUE THREAD

**Issue by GalGreenfield** [knowbee/rona-vscode-extension#4] opened 2020-12-28 14:25 UTC
Whenever I try running the command, I get a notification:
> Command 'convert require to import' resulted in an error (Running the contributed command: 'extension.Rona' failed.)

Could you please help me debug it? I got it before after new installation, and now, after reinstalling it again, the extension worked only once and then resulted in this.

**Comment by knowbee** [comment] 2020-12-28 17:11
I am unable to reproduce the same error you just reported, after uninstalling it and installing it , it still works as usual.

What version of vscode are you using? because it seems to be vscode issue rather than the extension itself?

Mine is:

`Version: 1.52.1
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0`

**Comment by GalGreenfield** [comment] 2020-12-29 22:07
My VS Code setup is:

```
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

I tried updating it just now and it says that no updates were available, so I suppose I'm on the latest version

**Comment by knowbee** [comment] 2020-12-30 05:53
Thank you, I will test it on a windows machine and try to debug the source of the problem.
In the meantime you can use the CLI version of rona

 ```cli 
npm i -g rona
```
Usage:
```cli
rona --path <pathName>
```

**Comment by knowbee** [comment] 2021-01-15 07:36
I could not reproduce such an error after debugging on a windows machine. Therefore I am going to close this issue.

**Closed as completed** 2021-01-15 14:17 UTC
